### ISSUE TITLE
Cannot update records in postgres, adminbro issues an insert instead of an update

### ISSUE THREAD

**Issue by synic** [SoftwareBrothers/adminjs-typeorm#29]
We just setup adminjs with nestjs and typeorm. We cannot edit records at all, as editing them and saving the form causes an insert instead of an update on all record types.

These are just standard typeorm entities, with a bigint autoincrement ID, nothing fancy. What are we doing wrong?

**Comment by synic** [comment]
@dziraf: how can we get help on this? We've got a problem here and with logging in, but no one seems to be replying to tickets

**Comment by dziraf** [comment]
Need more information as I have no issues in my projects. Please share your models. Relations with eager loading (`eager: true`) often cause various issues

**Comment by synic** [comment]
Sorry, I should have come up with a minimal repository. This one reproduces the problem: https://github.com/synic/adminjs-typeorm-minimal

I suspect it's our primary key that is causing the problem, but unsure how to resolve it: https://github.com/synic/adminjs-typeorm-minimal/blob/main/src/thing.entity.ts#L5

**Comment by synic** [comment]
@dziraf sorry to ping, I know github notifications are noisy but unsure if you saw this. And thanks in advance

**Comment by dziraf** [comment]
I did, I should have time to take a look tomorrow. In the meantime, can you check if, when loading your edit form (`edit` action's GET) the returned record has `record.id` and `record.params.id` defined?

**Comment by davedefiq** [comment]
Tracked down the issue to our Primary Key being of type bigint which in typeorm maps to a string, but is included in the Number data type mapping. This change seems to fix it: 

https://github.com/SoftwareBrothers/adminjs-typeorm/pull/31
