### ISSUE TITLE
Doesn't work with new version of TypeORM

### ISSUE THREAD

**Issue by AshotN** [SoftwareBrothers/adminjs-typeorm#41]
The adapter does not seem to work with new versions of TypeORM, simple things like selecting a row throw an error due to TypeORM's breaking changes.

**Comment by jamiecounsell** [comment]
The latest version of TypeOrm (0.3.X) is _significantly_ different so this will likely be a lot of work to update. This project's `package.json` does correctly indicate its peer dependency requirement:

```json
  "devDependencies": {
    // ...
    "typeorm": "~0.2.45",
    // ...
  }
```

I understand this will take some time for the contributors and community to update (I will also evaluate the effort myself) but it would be fantastic to at least get the maintainers to clarify if they intend to provide support for this version and (if possible) any ETA for that work.

I am starting out some new work and AdminJS may be a tool we evaluate but we are using TypeOrm 0.3.X so this would be a dependency.

In the meantime, when installing, you may see the error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: your-project@1.0.0
npm ERR! Found: typeorm@0.3.6
npm ERR! node_modules/typeorm
npm ERR!   typeorm@"^0.3.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typeorm@"~0.2.45" from @adminjs/typeorm@2.0.4
npm ERR! node_modules/@adminjs/typeorm
npm ERR!   @adminjs/typeorm@"*" from the root project
npm ERR! 
```
